/*
The default REST API tests for the server. Each cell can be executed on it's own but sometimes the results depend on what has been executed before.
*/
# Register and retrieve token
# @noRejectUnauthorized
POST https://admin:secret@localhost:46152/login
Content-Type application/json

# Assert successful login
?? status == 200

@jwtToken = {{response.parsedBody.token}}
###
# @noRejectUnauthorized
GET https://localhost:46152/v1/items
Authorization: Bearer {{jwtToken}}
###
# @noRejectUnauthorized
GET https://localhost:46152/v1/lists/1
Authorization: Bearer {{jwtToken}}
###
# The same authentication with JWT Tokens

# @noRejectUnauthorized
POST https://admin:secret@localhost:46152/login
Content-Type: application/json
###
@jwtToken={{response.parsedBody.token}}

# @noRejectUnauthorized

GET https://localhost:46152/v1/items
Authorization: Bearer {{jwtToken}}
###
# @noRejectUnauthorized

GET https://localhost:46152/test
###
# Create account and login

# @noRejectUnauthorized
POST https://admin:secret@localhost:46152/auth/create
Content-Type: application/json

{
    "id" : 0,
    "username" : "httpuser",
    "password" : "blablabla"
}

?? status == 201
###

@userId = {{response.parsedBody.ID}}

# @noRejectUnauthorized
POST https://{{userId}}:blablabla@localhost:46152/auth/login
Content-Type: application/json

{
    "id" : {{userId}},
    "username" : "httpuser",
    "password" : "blablabla"
}

?? status == 200
/*
# Trying a hardcoded one to check the login persistence
*/
###
@userId = 53952638
@password = blablabla
@username = httpuser

# @noRejectUnauthorized
POST https://{{userId}}:{{password}}@localhost:46152/auth/login
Content-Type: application/json

{
    "id" : {{userId}},
    "username" : "{{username}}",
    "password" : "{{password}}"
}

?? status == 200

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Fri, 29 Dec 2023 13:31:39 GMT
content-length: 208
connection: close
/*
# Trying if the token is valid for 3 minutes
*/
###
@jwtToken={{response.parsedBody.token}}

# @noRejectUnauthorized

GET https://localhost:46152/v1/test/auth
Authorization: Bearer {{jwtToken}}

?? status == 200

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Fri, 29 Dec 2023 13:31:41 GMT
content-length: 47
connection: close