services:
  mariadb:
    image: mariadb:lts
    hostname: database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      # This volume is only mounted and meant to be used for the initialization
      # The internal name seems to be important
      # Format: path on host:internal name
      - ./compose-db-setup:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_USER=root_user
      - MARIADB_ROOT_PASSWORD=<root_password>
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password

  # The server application
  application:
    image: shopping-list-server:0.8.13
    build:
      context: .
      dockerfile: Dockerfile.shopping-list-server
    restart: always
    ports:
      - "46152:46152"
    environment:
      - DB_CONFIG_FILE=resources/db.json
      - PRODUCTION=false
    volumes:
      # TODO: create and manage configuration folder during deployment
      - /srv/shopping-list-server/config:/resources
      - images:/images

volumes:
  db-data:
  images:
  