services:
  # Automatically restart the application when a new one is pushed
  watchtower:
    image: containrrr/watchtower:armhf-latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command:
      - --interval 120

  mariadb:
    image: mariadb:lts
    hostname: database
    restart: always
    volumes:
      - /srv/mariadb/data:/var/lib/mysql
      # This volume is only mounted and meant to be used for the initialization
      # The internal name seems to be important
      # Format: path on host:internal name
      - ./compose-db-setup:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_USER=root_user
      - MARIADB_ROOT_PASSWORD=<root_password>
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password

  # The server application
  application:
    image: registry.cloudsheeptech.com/shopping-list-server:latest
    build:
      context: .
      dockerfile: Dockerfile.shopping-list-server
    restart: always
    ports:
      - "46152:46152"
    environment:
      - CONFIG_FILE=../resources/config.json
      - PRODUCTION=true
    volumes:
      - /srv/shopping-list-server/:/
      - images:/images

volumes:
  db-data:
  images:
  