# Creating a new user, login, create a new list and share the list with all
@password = Password123
@username = Testuser Laptop

# @noRejectUnauthorized
POST https://localhost:46152/auth/create
Content-Type: application/json
{
    "ID" : 0,
    "Username" : "{{username}}",
    "Password" : "{{password}}"
}

?? status == 201

@userId = {{response.parsedBody.ID}}

HTTP/1.1 201  - Created
content-type: application/json; charset=utf-8
date: Thu, 22 Feb 2024 14:47:14 GMT
content-length: 177
connection: close
###
# Login

@userId = 1704291720
@username = Testuser Laptop
@password = Password123

# @noRejectUnauthorized
POST https://localhost:46152/auth/login
Content-Type: application/json
{
    "id" : {{userId}},
    "username" : "{{username}}",
    "password" : "{{password}}"
}

@jwtToken={{response.parsedBody.token}}

?? status == 200

HTTP/1.1 200  - OK
content-type: application/json; charset=utf-8
date: Thu, 22 Feb 2024 14:47:30 GMT
content-length: 220
connection: close
###
# Create list

@listname = Shared Test List 2
@itemName = Shared Test Item 2
@itemName2 = Second Testitem 222

# @noRejectUnauthorized
POST https://localhost:46152/v1/list
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "ListId" : 1,
    "Name" : "{{listname}}",
    "CreatedBy": {
        "ID": {{userId}},
        "Name": "{{username}}"
    },
    "Created": "2024-02-21T16:17:45Z",
    "LastEdited": "2024-02-22T10:17:45Z",
    "Items": [
        {
            "Name": "{{itemName}}",
            "Icon": "",
            "Quantity": 1,
            "Checked": false,
            "AddedBy" : {{userId}}
        },
        {
            "Name": "{{itemName2}}",
            "Icon": "",
            "Quantity": 1,
            "Checked": false,
            "AddedBy": {{userId}}
        }
    ]
}

?? status == 201

HTTP/1.1 201  - Created
date: Thu, 22 Feb 2024 14:47:30 GMT
content-length: 0
connection: close
###
# Share created list

@userId = 1704291720
@shareUserId = 269481484
@shareListId = 1

# @noRejectUnauthorized
POST https://localhost:46152/v1/share/{{shareListId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "ListId" : {{shareListId}},
    "CreatedBy" : {{userId}},
    "SharedWith" : {{shareUserId}},
    "Created" : "2024-02-21T16:17:45Z"
}

?? status == 201

{{response}}

HTTP/1.1 201  - Created
content-type: application/json; charset=utf-8
date: Thu, 22 Feb 2024 14:06:18 GMT
content-length: 114
connection: close